### ISSUE TITLE
Button not working with Postgres Datasource

### ISSUE THREAD

**Issue by asnakep** [speakyourcode/grafana-button-panel#1]
Hello,

I love this button, but unfortunately is not working with Postgres Datasources.
I'm using the json returned by query inspector, only the query part. 
Button return 200 ok message, but the action defined in datasource (a table update) doesn't works.
The datasource itself is working fine.

Here my query:

{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1610432023688",
      "to": "1610432323689",
      "queries": [
        {
          "intervalMs": 60000,
          "maxDataPoints": 934,
          "rawSql": "UPDATE schema_name.table_name set flag=1 where flag=0",
          "format": "table"
        }
      ]
   }
 }
}

Also tried to reduce it as 

{
	"queries": {
		"rawSql": "UPDATE schema_name.table_name set flag=1 where flag=0",
		"format": "table"
	}
}

Could you please advice on this?

Many thanks in advance,
best regards,
Emanuele

**Comment by speakyourcode** [comment]
The problem is that you're adding "queries", here is an example to create a database with postgres:
```
{
   "rawSql":"CREATE DATABASE foo;",
   "format":"table"
}
```
And to delete it:
```
{
   "rawSql":"DROP DATABASE foo;",
   "format":"table"
}
```

**Comment by asnakep** [comment]
Hello,

many thanks I'll try within an hour

Cheers

**Comment by asnakep** [comment]
Hello,

thanks so much again, it works.
Just made grafana execute commands, scripts and more.

Kind regards
Emanuele
