### ISSUE TITLE
Does not works with grafana cloud, bad query endpoint

### ISSUE THREAD

**Issue by Hivanoe** [speakyourcode/grafana-button-panel#11]
It uses the old endpoint (/api/tsdb/query), it should use instead /api/ds/query
see here https://github.com/grafana/grafana/pull/45238

**Comment by speakyourcode** [comment]
Hi, we are planning to update to Grafana 9 in November. We'll fix this then.

**Comment by Hivanoe** [comment]
I saw there is new release compatible with grafana 9
but I can't see it on the grafana cloud plugin repository (last version is  0.2.2) ....  will it be added ?

**Comment by speakyourcode** [comment]
fixed in v0.3.2
