### ISSUE TITLE
Plugin does not work in newer Version than v8.5.0 due to API change

### ISSUE THREAD

**Issue by bwint** [speakyourcode/grafana-button-panel#12]
Hi!

After upgrading my Grafana instance to v9.0.3 I noticed that I'm getting 404 Errors after clicking on a button:
![image](https://user-images.githubusercontent.com/22859417/179458191-f5551d0f-b92b-4427-9463-8030302bed43.png)

The 404 error is cause by trying to call the `/api/tsdb/query` path.
According to the [Grafana v8.5.0 documentation](https://grafana.com/docs/grafana/v8.5/http_api/data_source/#deprecated-resources) the `/api/tsdb/query` path is deprecated.

So since v9.0.x the new path need to be `/api/ds/query` according to the [docs](https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#query-a-data-source).
At least it looks like the POST body format stayed the same.

Using the [Health API](https://grafana.com/docs/grafana/latest/developers/http_api/other/#returns-health-information-about-grafana) it should be possible to determine the current Grafana version before sending the API call according to the button click.

**Comment by PepperJo** [comment]
+1

**Comment by ingaa85** [comment]
+1

**Comment by mekochanski** [comment]
+1
any chances for a fix?

**Comment by speakyourcode** [comment]
Hi, we are planning to update to Grafana 9 in November. We'll fix this then.

**Comment by GaMeRaM** [comment]
Seems like plugin has been fixed. Is it possible to release new version on grafana repo?
@speakyourcode

**Comment by okoren-corcentric** [comment]
Could you please add a new release of your plugin to https://grafana.com/grafana/plugins/speakyourcode-button-panel/ as well?
Thanks in advance!

**Comment by PapaRoach25** [comment]
Could you please add a new release of your plugin to https://grafana.com/grafana/plugins/speakyourcode-button-panel/ as well?
Thanks in advance!

**Comment by speakyourcode** [comment]
It's waiting for approval
![image](https://user-images.githubusercontent.com/58657886/206672455-465f9577-9648-4e2a-8c58-53c9acc96c0d.png)
In the meantime, you can download it from the [release page](https://github.com/speakyourcode/grafana-button-panel/releases/tag/v0.3.2).

**Comment by speakyourcode** [comment]
v0.3.2 has been approved
