### ISSUE TITLE
specify database in the query

### ISSUE THREAD

**Issue by tonylee2016** [speakyourcode/grafana-button-panel#4]
is it possible to support database selection (as a panel variable) in the query?  like in `DROP MEASUREMENT` ?
I think INFLUXQL does not support configuring the database in the query. But if you are using the REST API, the database can be specified. Can we support something like this?

{
  "query": "DROP MEASUREMENT \"$measurement_name\"”,
  **"db": "$database_name"**,
  "rawQuery": true,
  "resultFormat": "time_series"
}

**Comment by speakyourcode** [comment]
This plugin goes through datasources, not REST API, with the Grafana Influx Datasource, you connect to a specific database, so you can't have that as an option in the query. You would need a custom Influx Datasource for that, and have a template Grafana variable with the DB name, that you then use in the query

**Comment by tonylee2016** [comment]
> This plugin goes through datasources, not REST API, with the Grafana Influx Datasource, you connect to a specific database, so you can't have that as an option in the query. You would need a custom Influx Datasource for that, and have a template Grafana variable with the DB name, that you then use in the query

I have defined a grafana datasource variable, however it is not recognized by the plugin (not showing under the "Datasource
Choose the Datasource for the query" option)

**Comment by speakyourcode** [comment]
the Datasource drop down shows all available Datasources. A template variable won't be shown on that menu, but they can be used in the query

**Comment by tonylee2016** [comment]
> the Datasource drop down shows all available Datasources. A template variable won't be shown on that menu, but they can be used in the query

**Comment by tonylee2016** [comment]
> the Datasource drop down shows all available Datasources. A template variable won't be shown on that menu, but they can be used in the query

how to include a data source variable in the query? using "datasourceId" did not work.

**Comment by tonylee2016** [comment]
turns out it is just called "datasource"

**Comment by louting1989** [comment]
hello, i also want to use  a template variable MYSQL database in the query. could you please tell me how to use it. many thanks~
