### ISSUE TITLE
hello, i also want to use  a template variable MYSQL database in the query. could you please tell me how to use it. many thanks~

### ISSUE THREAD

**Issue by louting1989** [speakyourcode/grafana-button-panel#5]
hello, i also want to use  a template variable MYSQL database in the query. could you please tell me how to use it. many thanks~

_Originally posted by @louting1989 in https://github.com/speakyourcode/grafana-button-panel/issues/4#issuecomment-885339925_

**Comment by louting1989** [comment]
{
     "datasource": "${MYSQL_DB}",
      "format": "table",
      "rawSql": "delete from mydb where id >0"
    }

i write the query as above. but it dosen't work in the right database.

**Comment by speakyourcode** [comment]
Hi, it's exactly like in the example with PostgreSQL in the Readme:
```
{
  "rawSql": "DROP DATABASE $mydb;",
  "format": "table"
}
```

**Comment by louting1989** [comment]
![image](https://user-images.githubusercontent.com/26212660/128994460-8be6b0e0-5981-4347-bb37-96bdd43b8a36.png)

hello, my query is :
{
      "format": "table",
      "rawSql": "INSERT INTO `sys`.`test` (`id`,`tt`) VALUES(0,0) $MYSQL_DB;"
}
but it showed "query missing datasurceid"

**Comment by louting1989** [comment]
![image](https://user-images.githubusercontent.com/26212660/128996637-9c6b1eb9-bf51-4646-8845-36f3305379ed.png)

as the above picture, i didn't select the Datasource. my data source is the variable "$MYSQL_DB"

**Comment by louting1989** [comment]
so could you tell me how to use this panel in "insert function" for a template variable MYSQL database. thank you~

**Comment by speakyourcode** [comment]
No, that doesn't work, you have to select a datasource. In your case, configure a mysql datasource and select it in the menu. The plugin doesn't send the requests from the browser, but from the Grafana backend, through datasources

**Comment by louting1989** [comment]
ok, got it. thank you~
