### ISSUE TITLE
"Plugin not registered" error with Grafana 8.0.2.

### ISSUE THREAD

**Issue by luiscua** [speakyourcode/grafana-button-panel#7]
Thank you for this very useful plugin, unfortunately it is not working for me with a "marcusolsson-json-datasource" datasource. I am using the dockerized version of grafana 8.2.0 and I have the following error on grafana logs:

error="plugin not registered" 

On the front-end the error is "Metric request error". 

there is not a problem on the server api side (a flask microservice) because I cannot even see the requests from grafana.

**Comment by speakyourcode** [comment]
this should not happen with v0.3.2
