### ISSUE TITLE
When edit any properties, all buttons collapse

### ISSUE THREAD

**Issue by peterprvy** [speakyourcode/grafana-button-panel#9]
I am editing any property (in editor), like Query, Color , ...  still after pressing the key, everything is packed

for example, I press the space key at the specified location

![image](https://user-images.githubusercontent.com/36068077/157503576-95a8fc6c-427a-4820-8fcd-528c687fa6dc.png)

the editor was packed

![image](https://user-images.githubusercontent.com/36068077/157503183-3e4f2a34-f071-40d2-9562-e07a1cdbe2fe.png)

**Comment by peterprvy** [comment]
You should probably wait to press Apply or Save

![image](https://user-images.githubusercontent.com/36068077/157503989-f70fa868-6673-4c4b-88e7-8bf1ede12664.png)


in source code, edit all property invoke onChange


onChange={(e: SelectableValue<string>) =>
                updateButtons(i, { datasource: e.value })
              }

**Comment by aeshaynes** [comment]
This is also happening to me when using Grafana v8.3.4

**Comment by speakyourcode** [comment]
We'll fix this in November

**Comment by speakyourcode** [comment]
Grafana has changed the behavior of the `onChange` event, as a workaround, we have added an Apply button for this in v0.3.2
